fix VAR handling due to deprecated $VAR expansion feature
Error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: variable substitution using $VAR has been deprecated in favor of ${VAR} and ${env:VAR} - please update $MY_NODE_NAME or tem
porarily disable the confmap.unifyEnvVarExpansion feature gate
│